spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_db?createDatabaseIfNotExist=true
    username: bookstore_dev_rw
    password: dev_database_bookstore_pass
